spring.application.name=backend

spring.datasource.url=jdbc:postgresql://localhost:5433/rumbou
spring.datasource.username=rumbou
spring.datasource.password=rumbou

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
